name_exp: "AD vs CN MiNiT"
result_path: "./results/ad_cn_minit_2/"
image_size: 64
global_params:
    device: 'cuda:0'
model_params:
    model_name: "MiNiT"
    block_size: 8
    image_size: 64
    patch_size: 8
    num_classes: 1
    channels: 1
    dim: 128
    depth: 6
    heads: 4
    mlp_dim: 309
training_params:
    lr: 0.005
    count_folds_splits: 10
    use_checkpoint: False
    verbose_make_dataset: True
    verbose_train: True
    thr_metirc: 0.5
    batch_size: 6
    epoch_num: 4